### ISSUE TITLE
terser-deno fails TS check with Deno 1.22

### ISSUE THREAD

**Issue by shah** [lumeland/terser-deno#3]
@oscarotero `terser-deno` breaks in Deno 1.21.3 depends on [source_map](https://deno.land/x/source_map@0.7.4/mod.js) which uses unpinned Deno `std` libraries (meaning the latest version of `std`, which requires Deno 1.22, is picked up). If you get a minute, please add repo pinning so that it does not depend on latest Deno `std/fs` and `std/path` libraries.

**Comment by oscarotero** [comment]
Hi, @shah No problem, but I couldn't find any in `terser-deno` or `deno-source-map` unpinned dependency. Can you point me where this happens?

**Comment by shah** [comment]
Sure @oscarotero below is one example (if you search for `/std/` you'll see them):

![image](https://user-images.githubusercontent.com/47497/170823155-a3222cc2-ff84-41ee-b819-f0aa0e0b5dd8.png)

Thanks for the module!

**Comment by oscarotero** [comment]
Ok, I just created the 5.12.2 tag that should fix this error.

**Comment by shah** [comment]
It worked, thanks!
